reponame: code.arista.io/mfw/build
description: |
  MFW build utilities
users:
  maintainers:
    - abriles@arista.com
    - al.parker@arista.com
    - acooke@arista.com
    - avinash.dige@arista.com
    - crasmussen@arista.com
    - cblaise@arista.com
    - dhadarau@arista.com
    - donal@arista.com
    - iramasamy@arista.com
    - jphillips@arista.com
    - jsommerville@arista.com
    - k.skrzypczyn@arista.com
    - ksridhar@arista.com
    - sdelafond@arista.com
    - smitropoulos@arista.com
    - sumedha.game@arista.com
    - utkarsh.pratapsingh@arista.com
    - vishal.mane-ext@arista.com
  watchers:
    - bruce@arista.com
    - cmercer@arista.com
    - drush@arista.com
    - jcoffin@arista.com
    - manoj@arista.com
    - prashant.karunakaran@arista.com
    - sheck@arista.com
    - tkovalev@arista.com

x-github-bridge:
  # adding tests as separate entries for better visibility
  reviews:
    - image: test/build-floor
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: test/toolchain
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: test/toolchain-glibc
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: test/golang
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: test/golang-glibc
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: test/world
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: test/world-glibc
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: tests/renovate-json5
      events:
        - type: pull_request
          branch-re: ^main$
        - type: merge_group
          branch-re: ^main$
        - type: push
          branch-re: ^main$

x-bar:
  version: production

ObsoleteNames:
  - github.com/untangle/mfw_build

epoch: 1
